name: ARM64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm64
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Build
        run: cargo build --release
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-binary
          path: target/release/otlp_write_demo
