[package]
name = "otlp_write_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = "0.30"
opentelemetry-otlp = "0.30"
opentelemetry_sdk = "0.30"
tokio = { version = "1", features = ["full"] }
